### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/CTDL2schema.org#3]
We need examples of people describing relevant credentials on the web. This shows where the schema.org markup may be used, gives an indication of what information may be provided and how, and helps define the scope of what we are describing (see issue #2).

I'll start with:
SQA (Scottish qualifications authority) http://www.sqa.org.uk/sqa/41278.html

**Comment by stuartasutton** [comment]
- (Connecting Credentials) http://connectingcredentials.org/framework-detail/ 
- (Board of Certified Safety Professionals) http://www.bcsp.org/Certifications
- (Degree Qualifications Framework) http://degreeprofile.org/read-the-dqp/dqp-cover/
- (Common Core State Standards (Mathematics)) http://www.corestandards.org/Math/

**Comment by philbarker** [comment]
Noting a few more examples of people describing educaitonal and occupational credentials on the web
* Microsoft Certifications (https://www.microsoft.com/en-gb/learning/certification-overview.aspx) (also Cisco and Google et al)
* OpenBadges (https://openbadges.org/)
* City and Guilds qualifications (http://www.cityandguilds.com/qualifications-and-apprenticeships#fil=uk)
* EU Qualification frameworks (https://ec.europa.eu/ploteus/en/compare)
* Framework for Qualifications of the European Higher Education Area (http://ecahe.eu/w/index.php/Framework_for_Qualifications_of_the_European_Higher_Education_Area)

So far there seem to equal mix of those describing credentials on offer and those describing the frameworks for classifying credentials. Both are useful. 

I think we have enough numerically, but it would be useful if people would check that we have covered the full range credentials that is in scope. (academic, vocational, certifications, degrees...driving licenses? J)

**Comment by philbarker** [comment]
Examples are now at https://www.w3.org/community/eocred-schema/wiki/Examples_of_sites_with_credential_information
