### ISSUE TITLE
Use case outlines

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/CTDL2schema.org#4]
I have looked through the CTDL use cases and selected those that look relevant to schema.org, that is mostly those that relate to search and not to a specific app. You can see outlines of these use cases at https://goo.gl/gqwYKB 
Feel free to comment and/or edit in the document, but it would help if you edit in "suggesting" mode (click the pen icon at the top right), or make suggestions by replying to this.

**Comment by westurner** [comment]
Here's the latest version of the Use Cases document:
https://www.w3.org/community/eocred-schema/wiki/Use_Cases

**Comment by philbarker** [comment]
@westurner  Thanks. I should have posted that. It means we can close this issue
